<div>
    <x-app.layout>
        <x-dashboard
            :activePermissions="$activePermissions"
            :courses="$courses"
            :alumns="$alumns"
            :courseId="$courseId"
            :salidasHoy="$salidasHoy"
            :maxDailyPerAlumn="$maxDailyPerAlumn"
            :permissionDuration="$permissionDuration"
            :bathrooms="$bathrooms"
            :currentCountByBathroom="$currentCountByBathroom"
            :maxPermissionsByBathroom="$maxPermissionsByBathroom"
        />
    </x-app.layout>
</div>